# Generated by Django 4.1.1 on 2023-09-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_downloadrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadrecord',
            options={'verbose_name': '下載紀錄', 'verbose_name_plural': '下載紀錄'},
        ),
    ]
