# Generated by Django 4.1.1 on 2023-09-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_downloadrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('can_export_all_models', 'Can export all models')]},
        ),
    ]
