# Generated by Django 4.1.1 on 2023-10-10 01:54

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("user", "0004_alter_myuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHistory",
            fields=[],
            options={
                "verbose_name_plural": "編輯歷程",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
