# Generated by Django 4.1.1 on 2024-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_changeSecurityQuestion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='securityQuestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
