# Generated by Django 4.1.1 on 2024-06-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_is_changesecurityquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_changeSecurityQuestion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
