# Generated by Django 4.1.1 on 2024-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_userprofile_is_changesecurityquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_verified_code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
