# Generated by Django 4.1.1 on 2024-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_userprofile_has_verified_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="has_verified_code",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_viewed_verification",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
