# Generated by Django 4.1.1 on 2023-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_tag_latestevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrabSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CrabSite',
            },
        ),
        migrations.CreateModel(
            name='WaterQualityManualSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'WaterQualityManualSite',
            },
        ),
    ]
