# Generated by Django 4.1.1 on 2023-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_crabsite_waterqualitymanualsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitymanualsite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualsite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
