# Generated by Django 4.1.1 on 2023-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_waterqualitymanualsite_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenthicOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('site', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=6)),
                ('cw', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('mm', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('sc', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=6, null=True)),
                ('co', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('s_temp', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('t_sal', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True)),
                ('s_ph', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('w_temp', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('w_ph', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('cond', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('do', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('w_sal', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('turb', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=7, null=True)),
                ('orp', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'BenthicOrganism',
            },
        ),
        migrations.CreateModel(
            name='CrabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('site', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=6)),
                ('Mbr', models.IntegerField(default=0)),
                ('Mb', models.IntegerField(default=0)),
                ('Ma', models.IntegerField(default=0)),
                ('Hf', models.IntegerField(default=0)),
                ('Hd', models.IntegerField(default=0)),
                ('Hp', models.IntegerField(default=0)),
                ('Me', models.IntegerField(default=0)),
                ('Sb', models.IntegerField(default=0)),
                ('Sl', models.IntegerField(default=0)),
                ('It', models.IntegerField(default=0)),
                ('If', models.IntegerField(default=0)),
                ('Oc', models.IntegerField(default=0)),
                ('Al', models.IntegerField(default=0)),
                ('Ta', models.IntegerField(default=0)),
                ('Gb', models.IntegerField(default=0)),
                ('Xf', models.IntegerField(default=0)),
                ('Pa', models.IntegerField(default=0)),
                ('Pp', models.IntegerField(default=0)),
                ('Tc', models.IntegerField(default=0)),
                ('Ppi', models.IntegerField(default=0)),
                ('Mv', models.IntegerField(default=0)),
                ('Charybids_sp', models.IntegerField(default=0)),
                ('Mt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Crab',
            },
        ),
    ]
