# Generated by Django 4.1.1 on 2023-07-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_benthicorganism_crabdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrabData',
            new_name='Crab',
        ),
    ]
