# Generated by Django 4.1.1 on 2023-07-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_crabdata_crab'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('site', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=6)),
                ('w_temp', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('w_ph', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('phmv', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=7, null=True)),
                ('orp', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=7, null=True)),
                ('cond', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('turb', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=7, null=True)),
                ('do', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('w_sal', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
                ('sg', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'WaterQualityManual',
            },
        ),
    ]
