# Generated by Django 4.1.1 on 2023-07-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_waterqualitymanual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='LatestEventTag',
        ),
        migrations.AlterModelTable(
            name='latesteventtag',
            table='LatestEventTag',
        ),
    ]
