# Generated by Django 4.1.1 on 2023-07-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_tag_latesteventtag_alter_latesteventtag_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'InterviewTag1',
            },
        ),
        migrations.CreateModel(
            name='InterviewTag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_tag1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewtag2_set', to='data.interviewtag1')),
            ],
            options={
                'db_table': 'InterviewTag2',
            },
        ),
        migrations.CreateModel(
            name='InterviewTag3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_tag2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewtag3_set', to='data.interviewtag2')),
            ],
            options={
                'db_table': 'InterviewTag3',
            },
        ),
    ]
