# Generated by Django 4.1.1 on 2023-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_interviewtag1_interviewtag2_interviewtag3'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'InterviewStakeholder',
            },
        ),
    ]
