# Generated by Django 4.1.1 on 2023-07-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_interviewstakeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewpeople_set', to='data.interviewstakeholder')),
            ],
            options={
                'db_table': 'InterviewPeople',
            },
        ),
    ]
