# Generated by Django 4.1.1 on 2023-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_interviewpeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_people', models.ManyToManyField(to='data.interviewpeople')),
                ('interview_stakeholder', models.ManyToManyField(to='data.interviewstakeholder')),
                ('interview_tag2', models.ManyToManyField(to='data.interviewtag2')),
                ('interview_tag3', models.ManyToManyField(to='data.interviewtag3')),
            ],
            options={
                'db_table': 'InterviewContent',
            },
        ),
    ]
