# Generated by Django 4.1.1 on 2023-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_interviewcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcontent',
            name='date',
            field=models.DateField(),
        ),
    ]
