# Generated by Django 4.1.1 on 2023-07-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_interviewcontent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interviewcontent',
            name='updated_at',
        ),
    ]
