# Generated by Django 4.1.1 on 2023-07-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_interviewcontent_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewcontent',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='interviewcontent',
            old_name='date',
            new_name='interview_date',
        ),
    ]
