# Generated by Django 4.1.1 on 2023-07-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_text_interviewcontent_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
                ('refID', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('is_ebook', models.BooleanField()),
            ],
            options={
                'db_table': 'Literature',
            },
        ),
    ]
