# Generated by Django 4.1.1 on 2023-07-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_literature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='is_ebook',
            field=models.CharField(max_length=2),
        ),
    ]
