# Generated by Django 4.1.1 on 2023-07-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_literature_is_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
