# Generated by Django 4.1.1 on 2023-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_literature_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='is_ebook',
            field=models.BooleanField(max_length=2),
        ),
    ]
