# Generated by Django 4.1.1 on 2023-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_newstag'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('reporter', models.CharField(max_length=255)),
                ('photographer', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='news', to='data.newstag')),
            ],
            options={
                'db_table': 'News',
            },
        ),
    ]
