# Generated by Django 4.1.1 on 2023-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ResearchTag',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='research', to='data.researchtag')),
            ],
            options={
                'db_table': 'Research',
            },
        ),
    ]
