# Generated by Django 4.1.1 on 2023-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_researchtag_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='date',
        ),
        migrations.AddField(
            model_name='research',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
