# Generated by Django 4.1.1 on 2023-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_research_date_research_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
