# Generated by Django 4.1.1 on 2023-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_research_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crabsite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crabsite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
