# Generated by Django 4.1.1 on 2023-08-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_crabsite_latitude_alter_crabsite_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crabsite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crabsite',
            name='updated_at',
        ),
    ]
