# Generated by Django 4.1.1 on 2023-09-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_remove_crabsite_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualitymanualsite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waterqualitymanualsite',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='cond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='do',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='orp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='phmv',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='sg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='tds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='turb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='w_ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='w_sal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterqualitymanual',
            name='w_temp',
            field=models.FloatField(),
        ),
    ]
