# Generated by Django 4.1.1 on 2023-09-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_remove_waterqualitymanualsite_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterQualityManual',
        ),
    ]
