# Generated by Django 4.1.1 on 2023-09-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_delete_waterqualitymanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('site', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=6)),
                ('w_temp', models.FloatField()),
                ('w_ph', models.FloatField()),
                ('phmv', models.FloatField()),
                ('orp', models.FloatField()),
                ('cond', models.FloatField()),
                ('turb', models.FloatField()),
                ('do', models.FloatField()),
                ('tds', models.FloatField()),
                ('w_sal', models.FloatField()),
                ('sg', models.FloatField()),
            ],
            options={
                'db_table': 'WaterQualityManual',
            },
        ),
    ]
