# Generated by Django 4.1.1 on 2023-09-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_waterqualitymanual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterQualityManual',
            new_name='WaterQualityManualData',
        ),
        migrations.AlterModelTable(
            name='waterqualitymanualdata',
            table='WaterQualityManualData',
        ),
    ]
