# Generated by Django 4.1.1 on 2023-09-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_rename_waterqualitymanual_waterqualitymanualdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenthicOrganism',
            new_name='BenthicOrganismData',
        ),
        migrations.AlterModelTable(
            name='benthicorganismdata',
            table='BenthicOrganismData',
        ),
    ]
