# Generated by Django 4.1.1 on 2023-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_rename_benthicorganism_benthicorganismdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='co',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='cond',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='cw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='orp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='s_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='s_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='sc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='t_sal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='turb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='w_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='w_sal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benthicorganismdata',
            name='w_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
