# Generated by Django 4.1.1 on 2023-09-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_alter_benthicorganismdata_co_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crab",
            name="If",
        ),
    ]
