# Generated by Django 4.1.1 on 2023-09-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0033_remove_crab_if"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Crab",
            new_name="CrabData",
        ),
    ]
