# Generated by Django 4.1.1 on 2023-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_rename_crab_crabdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='refID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
