# Generated by Django 4.1.1 on 2023-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_literature_link_alter_literature_refid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
