# Generated by Django 4.1.1 on 2023-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_research_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcontent',
            name='interview_tag2',
            field=models.ManyToManyField(blank=True, to='data.interviewtag2'),
        ),
        migrations.AlterField(
            model_name='interviewcontent',
            name='interview_tag3',
            field=models.ManyToManyField(blank=True, to='data.interviewtag3'),
        ),
    ]
