# Generated by Django 4.1.1 on 2023-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_crabdata_al_alter_crabdata_charybids_sp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='cond',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='orp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='phmv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='sg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='turb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='w_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='w_sal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymanualdata',
            name='w_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
