# Generated by Django 4.1.1 on 2023-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_waterqualitymanualdata_cond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('duty', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': '人員職務',
                'verbose_name_plural': '人員職務',
                'db_table': 'Staff',
            },
        ),
        migrations.AlterModelOptions(
            name='benthicorganismdata',
            options={'verbose_name': '底棲生物-人工數據-底質資料', 'verbose_name_plural': '底棲生物-人工數據-底質資料'},
        ),
        migrations.AlterModelOptions(
            name='crabdata',
            options={'verbose_name': '底棲生物-人工數據-螃蟹資料', 'verbose_name_plural': '底棲生物-人工數據-螃蟹資料'},
        ),
        migrations.AlterModelOptions(
            name='crabsite',
            options={'verbose_name': '底棲生物-人工點位', 'verbose_name_plural': '底棲生物-人工點位'},
        ),
        migrations.AlterModelOptions(
            name='homepagephoto',
            options={'verbose_name': '首頁照片', 'verbose_name_plural': '首頁照片'},
        ),
        migrations.AlterModelOptions(
            name='latestevent',
            options={'verbose_name': '最新消息-內容', 'verbose_name_plural': '最新消息-內容'},
        ),
        migrations.AlterModelOptions(
            name='latesteventtag',
            options={'verbose_name': '最新消息-標籤', 'verbose_name_plural': '最新消息-標籤'},
        ),
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name': '地方文獻', 'verbose_name_plural': '地方文獻'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新聞報導-內容', 'verbose_name_plural': '新聞報導-內容'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name': '新聞報導-標籤', 'verbose_name_plural': '新聞報導-標籤'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': '相關研究-內容', 'verbose_name_plural': '相關研究-內容'},
        ),
        migrations.AlterModelOptions(
            name='researchtag',
            options={'verbose_name': '相關研究-標籤', 'verbose_name_plural': '相關研究-標籤'},
        ),
        migrations.AlterModelOptions(
            name='waterqualitymanualdata',
            options={'verbose_name': '水質觀測-人工數據', 'verbose_name_plural': '水質觀測-人工數據'},
        ),
        migrations.AlterModelOptions(
            name='waterqualitymanualsite',
            options={'verbose_name': '水質觀測-人工點位', 'verbose_name_plural': '水質觀測-人工點位'},
        ),
    ]
