# Generated by Django 4.1.1 on 2023-09-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_staff_alter_benthicorganismdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewcontent',
            options={'verbose_name': '訪談資料-內容', 'verbose_name_plural': '訪談資料-內容'},
        ),
        migrations.AlterModelOptions(
            name='interviewpeople',
            options={'verbose_name': '訪談資料-受訪者', 'verbose_name_plural': '訪談資料-受訪者'},
        ),
        migrations.AlterModelOptions(
            name='interviewstakeholder',
            options={'verbose_name': '訪談資料-受訪對象', 'verbose_name_plural': '訪談資料-受訪對象'},
        ),
        migrations.AlterModelOptions(
            name='interviewtag1',
            options={'verbose_name': '訪談資料-標籤1', 'verbose_name_plural': '訪談資料-標籤1'},
        ),
        migrations.AlterModelOptions(
            name='interviewtag2',
            options={'verbose_name': '訪談資料-標籤2', 'verbose_name_plural': '訪談資料-標籤2'},
        ),
        migrations.AlterModelOptions(
            name='interviewtag3',
            options={'verbose_name': '訪談資料-標籤3', 'verbose_name_plural': '訪談資料-標籤3'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
