# Generated by Django 4.1.1 on 2023-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_interviewcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
