# Generated by Django 4.1.1 on 2023-09-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_interviewcontent_download_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewcontent',
            old_name='download',
            new_name='download_volume',
        ),
        migrations.RenameField(
            model_name='interviewpeople',
            old_name='download',
            new_name='download_volume',
        ),
        migrations.RenameField(
            model_name='interviewstakeholder',
            old_name='download',
            new_name='download_volume',
        ),
        migrations.RenameField(
            model_name='interviewtag1',
            old_name='download',
            new_name='download_volume',
        ),
        migrations.RenameField(
            model_name='interviewtag2',
            old_name='download',
            new_name='download_volume',
        ),
        migrations.RenameField(
            model_name='interviewtag3',
            old_name='download',
            new_name='download_volume',
        ),
    ]
