# Generated by Django 4.1.1 on 2023-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_rename_download_interviewcontent_download_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstakeholder',
            name='optionId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
