# Generated by Django 4.1.1 on 2023-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_interviewstakeholder_optionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstakeholder',
            name='download_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewstakeholder',
            name='search_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
