# Generated by Django 4.1.1 on 2023-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_alter_interviewstakeholder_download_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcontent',
            name='download_volume',
        ),
        migrations.RemoveField(
            model_name='interviewcontent',
            name='search_volume',
        ),
        migrations.AlterField(
            model_name='interviewpeople',
            name='download_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewpeople',
            name='search_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag1',
            name='download_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag1',
            name='search_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag2',
            name='download_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag2',
            name='search_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag3',
            name='download_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='interviewtag3',
            name='search_volume',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
