# Generated by Django 4.1.1 on 2023-09-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_remove_interviewcontent_download_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewpeople',
            name='download_volume',
        ),
        migrations.RemoveField(
            model_name='interviewpeople',
            name='search_volume',
        ),
        migrations.RemoveField(
            model_name='interviewstakeholder',
            name='download_volume',
        ),
        migrations.RemoveField(
            model_name='interviewstakeholder',
            name='search_volume',
        ),
        migrations.RemoveField(
            model_name='interviewtag1',
            name='download_volume',
        ),
        migrations.RemoveField(
            model_name='interviewtag1',
            name='search_volume',
        ),
    ]
