# Generated by Django 4.1.1 on 2023-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0048_remove_interviewpeople_download_volume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crabdata",
            name="Pb",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
