# Generated by Django 4.1.1 on 2024-03-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0049_crabdata_pb"),
    ]

    operations = [
        migrations.AddField(
            model_name="crabdata",
            name="Mth",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
