# Generated by Django 4.2.14 on 2025-06-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_crabdata_mth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchesIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='問題描述')),
                ('identity', models.CharField(help_text='例如：治理機關、研究單位、生產者', max_length=255, verbose_name='提問人身份')),
                ('link', models.URLField(max_length=500, verbose_name='連結')),
            ],
            options={
                'verbose_name': '聚焦主題',
                'verbose_name_plural': '聚焦主題',
                'db_table': 'ResearchesIssue',
            },
        ),
    ]
