# Generated by Django 4.2.14 on 2025-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_researchesissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='資料年份')),
                ('county_code', models.CharField(max_length=10, verbose_name='縣市代碼')),
                ('county_name', models.CharField(max_length=20, verbose_name='縣市名稱')),
                ('town_code', models.CharField(max_length=10, verbose_name='鄉鎮市區代碼')),
                ('town_name', models.CharField(max_length=20, verbose_name='鄉鎮市區名稱')),
                ('village_code', models.CharField(max_length=20, verbose_name='村里代碼')),
                ('village_name', models.CharField(max_length=20, verbose_name='村里名稱')),
                ('household_count', models.CharField(max_length=10, verbose_name='戶數')),
                ('population_total', models.CharField(max_length=10, verbose_name='人口數')),
                ('population_density', models.CharField(max_length=10, verbose_name='人口密度')),
                ('sex_ratio', models.CharField(max_length=10, verbose_name='性別比')),
                ('dependency_ratio', models.CharField(max_length=10, verbose_name='扶養比')),
                ('child_dependency_ratio', models.CharField(max_length=10, verbose_name='扶幼比')),
                ('elderly_dependency_ratio', models.CharField(max_length=10, verbose_name='扶老比')),
                ('aging_index', models.CharField(max_length=10, verbose_name='老化指數')),
                ('crude_birth_rate', models.CharField(max_length=10, verbose_name='粗出生率')),
                ('crude_death_rate', models.CharField(max_length=10, verbose_name='粗死亡率')),
                ('natural_increase_rate', models.CharField(max_length=10, verbose_name='自然增加率')),
                ('social_increase_rate', models.CharField(max_length=10, verbose_name='社會增加率')),
                ('population_growth_rate', models.CharField(max_length=10, verbose_name='人口增加率')),
                ('age_0_14', models.CharField(max_length=10, verbose_name='0-14歲人口數')),
                ('age_15_64', models.CharField(max_length=10, verbose_name='15-64歲人口數')),
                ('age_65_up', models.CharField(max_length=10, verbose_name='65歲以上人口數')),
                ('data_collection_time', models.CharField(max_length=20, verbose_name='資料時間')),
            ],
            options={
                'verbose_name': '人口統計',
                'verbose_name_plural': '人口統計',
                'db_table': 'PopulationStats',
            },
        ),
        migrations.AddField(
            model_name='researchesissue',
            name='is_display',
            field=models.BooleanField(default=True, help_text='勾選後，該主題將顯示於前端頁面；未勾選則不顯示', verbose_name='是否顯示於前端頁面'),
        ),
    ]
