# Generated by Django 4.2.14 on 2025-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_populationstats_researchesissue_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchesissue',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='點擊數'),
        ),
        migrations.AlterField(
            model_name='researchesissue',
            name='is_display',
            field=models.BooleanField(default=True, help_text='（勾選後，該主題將顯示於前端頁面；未勾選則不顯示）', verbose_name='是否顯示於前端'),
        ),
    ]
