# Generated by Django 4.2.14 on 2025-09-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_researchesissue_hits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisheryFarmingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='年份')),
                ('horizontal_facilities_nation', models.CharField(max_length=20, verbose_name='平掛式設施(組)-全國')),
                ('horizontal_farmers_nation', models.CharField(max_length=20, verbose_name='平掛式養殖（戶）-全國')),
                ('horizontal_facilities_fangyuan', models.CharField(max_length=20, verbose_name='平掛式設施(組)-芳苑鄉')),
                ('horizontal_farmers_fangyuan', models.CharField(max_length=20, verbose_name='平掛式養殖（戶）-芳苑鄉')),
                ('horizontal_facilities_changhua', models.CharField(max_length=20, verbose_name='平掛式設施(組)-彰化縣')),
                ('horizontal_farmers_changhua', models.CharField(max_length=20, verbose_name='平掛式養殖（戶）-彰化縣')),
                ('stake_facilities_nation', models.CharField(max_length=20, verbose_name='插篊式設施(組)-全國')),
                ('stake_farmers_nation', models.CharField(max_length=20, verbose_name='插篊式養殖（戶）-全國')),
                ('stake_facilities_fangyuan', models.CharField(max_length=20, verbose_name='插篊式設施(組)-芳苑鄉')),
                ('stake_farmers_fangyuan', models.CharField(max_length=20, verbose_name='插篊式養殖（戶）-芳苑鄉')),
                ('stake_facilities_changhua', models.CharField(max_length=20, verbose_name='插篊式設施(組)-彰化縣')),
                ('stake_farmers_changhua', models.CharField(max_length=20, verbose_name='插篊式養殖（戶）-彰化縣')),
                ('hanging_facilities_nation', models.CharField(max_length=20, verbose_name='垂下式設施(棚)-全國')),
                ('hanging_farmers_nation', models.CharField(max_length=20, verbose_name='垂下式養殖（戶）-全國')),
                ('hanging_facilities_fangyuan', models.CharField(max_length=20, verbose_name='垂下式設施(棚)-芳苑鄉')),
                ('hanging_farmers_fangyuan', models.CharField(max_length=20, verbose_name='垂下式養殖（戶）-芳苑鄉')),
                ('hanging_facilities_changhua', models.CharField(max_length=20, verbose_name='垂下式設施(棚)-彰化縣')),
                ('hanging_farmers_changhua', models.CharField(max_length=20, verbose_name='垂下式養殖（戶）-彰化縣')),
                ('raft_facilities_nation', models.CharField(max_length=20, verbose_name='浮筏式設施(棚)-全國')),
                ('raft_farmers_nation', models.CharField(max_length=20, verbose_name='浮筏式養殖（戶）-全國')),
                ('raft_facilities_fangyuan', models.CharField(max_length=20, verbose_name='浮筏式設施(棚)-芳苑鄉')),
                ('raft_farmers_fangyuan', models.CharField(max_length=20, verbose_name='浮筏式養殖（戶）-芳苑鄉')),
                ('raft_facilities_changhua', models.CharField(max_length=20, verbose_name='浮筏式設施(棚)-彰化縣')),
                ('raft_farmers_changhua', models.CharField(max_length=20, verbose_name='浮筏式養殖（戶）-彰化縣')),
                ('longline_facilities_nation', models.CharField(max_length=20, verbose_name='延繩式設施(組)-全國')),
                ('longline_farmers_nation', models.CharField(max_length=20, verbose_name='延繩式養殖（戶）-全國')),
                ('longline_facilities_fangyuan', models.CharField(max_length=20, verbose_name='延繩式設施(組)-芳苑鄉')),
                ('longline_farmers_fangyuan', models.CharField(max_length=20, verbose_name='延繩式養殖（戶）-芳苑鄉')),
                ('longline_facilities_changhua', models.CharField(max_length=20, verbose_name='延繩式設施(組)-彰化縣')),
                ('longline_farmers_changhua', models.CharField(max_length=20, verbose_name='延繩式養殖（戶）-彰化縣')),
                ('total_farmers_nation', models.CharField(max_length=20, verbose_name='申報（調查）總戶數-全國')),
                ('total_farmers_fangyuan', models.CharField(max_length=20, verbose_name='申報（調查）總戶數-芳苑鄉')),
                ('total_farmers_changhua', models.CharField(max_length=20, verbose_name='申報（調查）總戶數-彰化縣')),
            ],
            options={
                'verbose_name': '養殖漁業統計',
                'verbose_name_plural': '養殖漁業統計',
                'db_table': 'FisheryFarmingStats',
            },
        ),
    ]
