# Generated by Django 4.2.14 on 2025-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_fisheryfarmingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='OysterFarmingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='年份')),
                ('horizontal_facilities_nation', models.CharField(max_length=20, verbose_name='全國 - 平掛式設施(組)')),
                ('horizontal_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 平掛式養殖（戶）')),
                ('horizontal_facilities_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 平掛式設施(組)')),
                ('horizontal_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 平掛式養殖（戶）')),
                ('horizontal_facilities_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 平掛式設施(組)')),
                ('horizontal_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 平掛式養殖（戶）')),
                ('stake_facilities_nation', models.CharField(max_length=20, verbose_name='全國 - 插篊式設施(組)')),
                ('stake_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 插篊式養殖（戶）')),
                ('stake_facilities_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 插篊式設施(組)')),
                ('stake_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 插篊式養殖（戶）')),
                ('stake_facilities_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 插篊式設施(組)')),
                ('stake_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 插篊式養殖（戶）')),
                ('hanging_facilities_nation', models.CharField(max_length=20, verbose_name='全國 - 垂下式設施(棚)')),
                ('hanging_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 垂下式養殖（戶）')),
                ('hanging_facilities_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 垂下式設施(棚)')),
                ('hanging_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 垂下式養殖（戶）')),
                ('hanging_facilities_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 垂下式設施(棚)')),
                ('hanging_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 垂下式養殖（戶）')),
                ('raft_facilities_nation', models.CharField(max_length=20, verbose_name='全國 - 浮筏式設施(棚)')),
                ('raft_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 浮筏式養殖（戶）')),
                ('raft_facilities_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 浮筏式設施(棚)')),
                ('raft_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 浮筏式養殖（戶）')),
                ('raft_facilities_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 浮筏式設施(棚)')),
                ('raft_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 浮筏式養殖（戶）')),
                ('longline_facilities_nation', models.CharField(max_length=20, verbose_name='全國 - 延繩式設施(組)')),
                ('longline_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 延繩式養殖（戶）')),
                ('longline_facilities_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 延繩式設施(組)')),
                ('longline_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 延繩式養殖（戶）')),
                ('longline_facilities_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 延繩式設施(組)')),
                ('longline_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 延繩式養殖（戶）')),
                ('total_farmers_nation', models.CharField(max_length=20, verbose_name='全國 - 申報（調查）總戶數')),
                ('total_farmers_fangyuan', models.CharField(max_length=20, verbose_name='芳苑鄉 - 申報（調查）總戶數')),
                ('total_farmers_changhua', models.CharField(max_length=20, verbose_name='彰化縣 - 申報（調查）總戶數')),
            ],
            options={
                'verbose_name': '牡蠣放養統計',
                'verbose_name_plural': '牡蠣放養統計',
                'db_table': 'OysterFarmingStats',
            },
        ),
        migrations.DeleteModel(
            name='FisheryFarmingStats',
        ),
    ]
