# Generated by Django 4.2.14 on 2025-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_oysterfarmingstats_delete_fisheryfarmingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisheryFarmingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='年份')),
                ('hard_clam_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='文蛤 - 養殖戶數')),
                ('hard_clam_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='文蛤 - 養殖面積（公頃）')),
                ('hard_clam_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='文蛤 - 在池-放養量（尾、粒、隻）')),
                ('hard_clam_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='文蛤 - 新放養-放養量（尾、粒、隻）')),
                ('hard_clam_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='文蛤 - 魚苗戶')),
                ('hard_clam_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='文蛤 - 養殖戶')),
                ('mullet_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='烏魚 - 養殖戶數')),
                ('mullet_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='烏魚 - 養殖面積（公頃）')),
                ('mullet_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='烏魚 - 在池-放養量（尾、粒、隻）')),
                ('mullet_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='烏魚 - 新放養-放養量（尾、粒、隻）')),
                ('mullet_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='烏魚 - 魚苗戶')),
                ('mullet_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='烏魚 - 養殖戶')),
                ('milkfish_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='虱目魚 - 養殖戶數')),
                ('milkfish_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='虱目魚 - 養殖面積（公頃）')),
                ('milkfish_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='虱目魚 - 在池-放養量（尾、粒、隻）')),
                ('milkfish_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='虱目魚 - 新放養-放養量（尾、粒、隻）')),
                ('milkfish_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='虱目魚 - 魚苗戶')),
                ('milkfish_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='虱目魚 - 養殖戶')),
                ('asiatic_clam_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='蜆 - 養殖戶數')),
                ('asiatic_clam_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='蜆 - 養殖面積（公頃）')),
                ('asiatic_clam_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='蜆 - 在池-放養量（尾、粒、隻）')),
                ('asiatic_clam_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='蜆 - 新放養-放養量（尾、粒、隻）')),
                ('asiatic_clam_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='蜆 - 魚苗戶')),
                ('asiatic_clam_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='蜆 - 養殖戶')),
                ('white_shrimp_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='白蝦 - 養殖戶數')),
                ('white_shrimp_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='白蝦 - 養殖面積（公頃）')),
                ('white_shrimp_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='白蝦 - 在池-放養量（尾、粒、隻）')),
                ('white_shrimp_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='白蝦 - 新放養-放養量（尾、粒、隻）')),
                ('white_shrimp_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='白蝦 - 魚苗戶')),
                ('white_shrimp_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='白蝦 - 養殖戶')),
                ('tilapia_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='吳郭魚 - 養殖戶數')),
                ('tilapia_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='吳郭魚 - 養殖面積（公頃）')),
                ('tilapia_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='吳郭魚 - 在池-放養量（尾、粒、隻）')),
                ('tilapia_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='吳郭魚 - 新放養-放養量（尾、粒、隻）')),
                ('tilapia_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='吳郭魚 - 魚苗戶')),
                ('tilapia_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='吳郭魚 - 養殖戶')),
                ('eel_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='鰻魚 - 養殖戶數')),
                ('eel_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='鰻魚 - 養殖面積（公頃）')),
                ('eel_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='鰻魚 - 在池-放養量（尾、粒、隻）')),
                ('eel_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='鰻魚 - 新放養-放養量（尾、粒、隻）')),
                ('eel_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='鰻魚 - 魚苗戶')),
                ('eel_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='鰻魚 - 養殖戶')),
                ('yamato_clam_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='日本黑蜆 - 養殖戶數')),
                ('yamato_clam_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='日本黑蜆 - 養殖面積（公頃）')),
                ('yamato_clam_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='日本黑蜆 - 在池-放養量（尾、粒、隻）')),
                ('yamato_clam_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='日本黑蜆 - 新放養-放養量（尾、粒、隻）')),
                ('yamato_clam_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='日本黑蜆 - 魚苗戶')),
                ('yamato_clam_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='日本黑蜆 - 養殖戶')),
                ('purple_clam_households_total', models.CharField(blank=True, max_length=32, null=True, verbose_name='西施貝 - 養殖戶數')),
                ('purple_clam_area_hectare', models.CharField(blank=True, max_length=64, null=True, verbose_name='西施貝 - 養殖面積（公頃）')),
                ('purple_clam_stocking_in_pond', models.CharField(blank=True, max_length=64, null=True, verbose_name='西施貝 - 在池-放養量（尾、粒、隻）')),
                ('purple_clam_stocking_new', models.CharField(blank=True, max_length=64, null=True, verbose_name='西施貝 - 新放養-放養量（尾、粒、隻）')),
                ('purple_clam_hatchery_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='西施貝 - 魚苗戶')),
                ('purple_clam_farmer_households', models.CharField(blank=True, max_length=32, null=True, verbose_name='西施貝 - 養殖戶')),
            ],
            options={
                'verbose_name': '養殖放養統計',
                'verbose_name_plural': '養殖放養統計',
                'db_table': 'FisheryFarmingStats',
            },
        ),
    ]
