# Generated by Django 4.2.14 on 2026-06-04 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_fisheryfarmingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=100, unique=True)),
                ('eventDate', models.DateField()),
                ('locationID', models.CharField(max_length=50)),
                ('waterTemperature', models.FloatField()),
                ('pH', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('hydrogenIon', models.FloatField()),
                ('oxidationReductionPotential', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('dissolvedOxygen', models.FloatField()),
                ('totalDissolvedSolids', models.FloatField()),
                ('salinity', models.FloatField()),
                ('specificGravity', models.FloatField()),
            ],
            options={
                'verbose_name': '水質調查',
                'verbose_name_plural': '水質調查',
                'db_table': 'depositar_water_quality',
            },
        ),
    ]
