# Generated by Django 4.2.14 on 2026-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_waterquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterquality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterquality',
            name='data_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterquality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
