# Generated by Django 4.2.14 on 2026-06-04 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_waterquality_created_at_waterquality_data_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sediment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=100, unique=True)),
                ('eventDate', models.DateField()),
                ('locationID', models.CharField(max_length=50)),
                ('soilTemperature', models.FloatField()),
                ('tidalPoolSalinity', models.FloatField()),
                ('soilWater', models.FloatField()),
                ('soilOrganicMatter', models.FloatField()),
                ('soilPH', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('medianGrainSize', models.FloatField()),
                ('sortingCoefficient', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': '底質調查',
                'verbose_name_plural': '底質調查',
                'db_table': 'depositar_sediment',
            },
        ),
    ]
