# Generated by Django 4.2.14 on 2026-06-04 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_sediment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=100, unique=True)),
                ('eventDate', models.DateField()),
                ('basisOfRecord', models.CharField(choices=[('MaterialEntity', 'MaterialEntity'), ('PreservedSpecimen', 'PreservedSpecimen'), ('FossilSpecimen', 'FossilSpecimen'), ('LivingSpecimen', 'LivingSpecimen'), ('HumanObservation', 'HumanObservation'), ('MaterialSample', 'MaterialSample'), ('MachineObservation', 'MachineObservation'), ('Event', 'Event'), ('Taxon', 'Taxon'), ('Occurrence', 'Occurrence'), ('MaterialCitation', 'MaterialCitation')], max_length=50)),
                ('scientificName', models.CharField(max_length=200)),
                ('vernacularName', models.CharField(max_length=200)),
                ('individualCount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('locality', models.CharField(max_length=200)),
                ('locationID', models.CharField(max_length=50)),
                ('decimalLatitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('decimalLongitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('geodeticDatum', models.CharField(max_length=50)),
                ('samplingProtocol', models.CharField(blank=True, max_length=200, null=True)),
                ('sampleSizeValue', models.FloatField(blank=True, null=True)),
                ('sampleSizeUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('samplingEffort', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': '蟹類調查',
                'verbose_name_plural': '蟹類調查',
                'db_table': 'depositar_crab',
            },
        ),
    ]
