# Generated by Django 4.2.14 on 2026-06-08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0060_crab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sediment",
            name="medianGrainSize",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="soilOrganicMatter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="soilPH",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="soilTemperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="soilWater",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="sortingCoefficient",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sediment",
            name="tidalPoolSalinity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="conductivity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="dissolvedOxygen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="hydrogenIon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="oxidationReductionPotential",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="pH",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="salinity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="specificGravity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="totalDissolvedSolids",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="turbidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="waterTemperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
